# Generated by Django 5.2.4 on 2025-08-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_thread_options_alter_thread_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-created_at']},
        ),
    ]
