# Generated by Django 5.2.5 on 2025-08-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_thread_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
